name: flutter_ws
description: A mobile Mediathek based on the MediathekView Web API.
version: 1.1.1+3

publish_to: 'none'

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: 2.0.0

dependencies:
  http: 0.12.2
  path_provider: 1.6.5
  sqflite: ^1.2.0
  uuid: ^1.0.3
  json_object_lite: ^2.0.0
  device_info: 0.4.2+1
  url_launcher: ^5.0.0
  logging: ^0.11.3+2
  synchronized: ^2.2.0
  flutter_downloader: ^1.4.4
  shimmer: ^1.0.0
  flutter_spinkit: ^3.1.0
  auto_size_text: ^1.0.0
  carousel_slider: ^1.4.1
  quiver: 2.1.3
  flutter_swiper : ^1.1.6
  flutter_staggered_grid_view: ^0.2.7
  video_player: ^1.0.1
  chewie: ^0.12.1+1
  wakelock: ^0.2.1+1
  flutter_launcher_icons: ^0.7.0
  shared_preferences: ^0.5.3+4
  intro_slider: ^2.2.9
  connectivity: ^0.4.8+2
  video_thumbnail: ^0.2.5+1
  countly_flutter: ^20.4.2
  giffy_dialog: ^1.8.0
  filesize: ^1.0.4

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/img/ard.png
      - assets/img/orf.png
      - assets/img/zdf.png
      - assets/img/wdr.png
      - assets/img/arte.png
      - assets/img/ndr.png
      - assets/img/3sat.png
      - assets/img/swr.png
      - assets/img/br.png
      - assets/img/dw.png
      - assets/img/hr.png
      - assets/img/kika.png
      - assets/img/mdr.png
      - assets/img/phoenix.png
      - assets/img/rbb.png
      - assets/img/srf.png
      - assets/img/MediathekViewLoading.png
      - assets/intro/intro_slider_1.png
      - assets/intro/intro_slider_2.png
      - assets/launcher/ic_launcher.png
      - assets/cast/ic_cast0_white.png
      - assets/cast/ic_cast1_white.png
      - assets/cast/ic_cast2_white.png
      - assets/cast/ic_cast_connected_white.png
      - assets/cast/ic_cast_white.png

  fonts:
    - family: OldStandard
      fonts:
        - asset: assets/fonts/OldStandard-Regular.ttf
          weight: 600
        - asset: assets/fonts/OldStandard-Bold.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
